//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaSize
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PizzaSize()
        {
            this.PizzaAssortiments = new HashSet<PizzaAssortiment>();
        }
    
        public int PizzaSizeID { get; set; }
        public string Size { get; set; }
        public int Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PizzaAssortiment> PizzaAssortiments { get; set; }
    }
}
