//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaAssortiment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PizzaAssortiment()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int PizzaAssortimentID { get; set; }
        public int PizzaID { get; set; }
        public int PizzaSizeID { get; set; }
        public decimal Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Pizza Pizza { get; set; }
        public virtual PizzaSize PizzaSize { get; set; }

        public override string ToString()
        {
            return $"{Pizza.PizzaName} {PizzaSize.Size}";
        }
    }
}
